package com.blood.javainstitute.db;
// Generated Oct 3, 2015 11:26:43 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Donor generated by hbm2java
 */
@Entity
@Table(name="donor"
    ,catalog="blood"
)
public class Donor  implements java.io.Serializable {


     private Integer iddonor;
     private BloodGroup bloodGroup;
     private Integer batchjsad;
     private byte[] nic;
     private Date bday;
     private byte[] email;
     private byte[] tel;
     private byte[] tel2;
     private byte[] path;
     private Integer graduateYear;

    public Donor() {
    }

	
    public Donor(BloodGroup bloodGroup) {
        this.bloodGroup = bloodGroup;
    }
    public Donor(BloodGroup bloodGroup, Integer batchjsad, byte[] nic, Date bday, byte[] email, byte[] tel, byte[] tel2, byte[] path, Integer graduateYear) {
       this.bloodGroup = bloodGroup;
       this.batchjsad = batchjsad;
       this.nic = nic;
       this.bday = bday;
       this.email = email;
       this.tel = tel;
       this.tel2 = tel2;
       this.path = path;
       this.graduateYear = graduateYear;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddonor", unique=true, nullable=false)
    public Integer getIddonor() {
        return this.iddonor;
    }
    
    public void setIddonor(Integer iddonor) {
        this.iddonor = iddonor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="blood_group_idblood_group", nullable=false)
    public BloodGroup getBloodGroup() {
        return this.bloodGroup;
    }
    
    public void setBloodGroup(BloodGroup bloodGroup) {
        this.bloodGroup = bloodGroup;
    }

    
    @Column(name="batchjsad")
    public Integer getBatchjsad() {
        return this.batchjsad;
    }
    
    public void setBatchjsad(Integer batchjsad) {
        this.batchjsad = batchjsad;
    }

    
    @Column(name="nic")
    public byte[] getNic() {
        return this.nic;
    }
    
    public void setNic(byte[] nic) {
        this.nic = nic;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="bday", length=10)
    public Date getBday() {
        return this.bday;
    }
    
    public void setBday(Date bday) {
        this.bday = bday;
    }

    
    @Column(name="email")
    public byte[] getEmail() {
        return this.email;
    }
    
    public void setEmail(byte[] email) {
        this.email = email;
    }

    
    @Column(name="tel")
    public byte[] getTel() {
        return this.tel;
    }
    
    public void setTel(byte[] tel) {
        this.tel = tel;
    }

    
    @Column(name="tel2")
    public byte[] getTel2() {
        return this.tel2;
    }
    
    public void setTel2(byte[] tel2) {
        this.tel2 = tel2;
    }

    
    @Column(name="path")
    public byte[] getPath() {
        return this.path;
    }
    
    public void setPath(byte[] path) {
        this.path = path;
    }

    
    @Column(name="graduate_year")
    public Integer getGraduateYear() {
        return this.graduateYear;
    }
    
    public void setGraduateYear(Integer graduateYear) {
        this.graduateYear = graduateYear;
    }




}


